require('configs.nvim-tree')
require('configs.nvim-web-devicons')
require('configs.telescope')
require('configs.catpuccin')
require('configs.lualine')
-- require('configs.coc') -- deprecated. Testing the nvim-cmp
require('configs.signs')
-- require('configs.copilot')
require('configs.move')
require('configs.supermaven')
require('configs.obsidian')
require('configs.nvim-cmp')
require('configs.mason')
require('configs.lsp-config')
-- require('configs.codeium')
require('configs.luasnip')
