-- require("mason-lspconfig").setup({
--   -- https://github.com/williamboman/mason-lspconfig.nvim
--   ensure_installed = { "ts_ls", "jdtls", "tailwindcss", "rust_analyzer" },
-- })

-- Specify how the border looks like
-- local border = {
--     { '╭', 'FloatBorder' },
--     { '─', 'FloatBorder' },
--     { '╮', 'FloatBorder' },
--     { '│', 'FloatBorder' },
--     { '╯', 'FloatBorder' },
--     { '─', 'FloatBorder' },
--     { '╰', 'FloatBorder' },
--     { '│', 'FloatBorder' },
-- }
-- 
-- -- Add the border on hover and on signature help
-- local handlers = {
--     ['textDocument/hover'] = vim.lsp.with(vim.lsp.handlers.hover, { border = border }),
--     ['textDocument/signatureHelp'] = vim.lsp.with(vim.lsp.handlers.signature_help, { border = border }),
-- }

-- Add border to the diagnostic popup window
